onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/clk21m
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/reset
add wave -noupdate -radix binary /tb/u_dut/u_sprite_draw/dot_state
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/sp_draw_state
add wave -noupdate -radix unsigned /tb/u_dut/u_line_buffer_xeven/adr
add wave -noupdate -radix unsigned /tb/u_dut/u_line_buffer_xeven/adr
add wave -noupdate -radix unsigned /tb/u_dut/u_line_buffer_xeven/q
add wave -noupdate /tb/u_dut/w_display_en
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/sp_en
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/dot_counter_x
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/eight_dot_state
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/ff_current_render_sp
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/render_sp
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/render_sp_num
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_y_address
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_x_address
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_pattern_num_address
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_pattern_l_address
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_pattern_r_address
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_color_address
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_render_read_address
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/vram_a
add wave -noupdate -radix hexadecimal /tb/u_dut/PRAMADR
add wave -noupdate -radix unsigned /tb/u_dut/PRAMDAT
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/vram_q
add wave -noupdate -divider {New Divider}
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/current_y
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/attribute_table_address
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/pattern_gentbl_address
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/vdp_s0_reset_timing
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/vdp_s5_reset_timing
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/current_render_sp
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/draw_xeven_adr
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/draw_xodd_adr
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/draw_xeven_write
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/draw_xodd_write
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/draw_xeven_pixel
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/draw_xodd_pixel
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/line_buffer_xeven_q
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/line_buffer_xodd_q
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/vdp_s0_sp_collision_incidence
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/vdp_s3_s4_sp_collision_x
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/vdp_s5_s6_sp_collision_y
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/reg_r1_sp_size
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/reg_r1_sp_zoom
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/reg_r8_col0_on
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/sp_mode2
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/w_attribute_address
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/w_y_pos
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/ff_render_y
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/ff_render_x
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/ff_render_pattern_l
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/ff_render_pattern_r
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/ff_render_pattern_num
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/ff_render_color
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/ff_render_ic
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/ff_render_cc
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/ff_render_ec
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/ff_draw_sp_num
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/ff_draw_state
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/w_draw_enable_8x8_normal
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/w_draw_enable_8x8_zoom
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/w_draw_enable_16x16_normal
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/w_draw_enable_16x16_zoom
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/w_draw_enable
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/w_draw_read
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/w_draw_write
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/w_draw_x0_pixel
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/w_draw_x1_pixel
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/ff_draw_x0
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/ff_draw_x1
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/ff_draw_pattern
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/ff_draw_color
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/ff_draw_ic
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/ff_draw_cc
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/ff_sp_enable
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/w_sp_final
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/ff_sp_final
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/w_draw_pattern_x0
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/w_draw_pattern_x1
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/w_line_buffer_x0_q
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/w_line_buffer_x1_q
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/w_draw_x0_last_active
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/w_draw_x0_last_sp_num
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/w_draw_x0_last_color
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/w_draw_x1_last_active
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/w_draw_x1_last_sp_num
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/w_draw_x1_last_color
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/w_draw_opacity
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/ff_vdp_s0_sp_collision_incidence
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/ff_vdp_s3456_sp_collision_xy_hold
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/ff_vdp_s3_s4_sp_collision_x
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/ff_vdp_s5_s6_sp_collision_y
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/w_next_render_sp
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/clk21m
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/reset
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/dot_state
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/eight_dot_state
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/sp_draw_state
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/sp_en
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/dot_counter_x
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/current_y
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/attribute_table_address
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/pattern_gentbl_address
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/vdp_s0_reset_timing
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/vdp_s5_reset_timing
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/current_render_sp
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/render_sp
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/render_sp_num
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/draw_xeven_adr
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/draw_xodd_adr
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/draw_xeven_write
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/draw_xodd_write
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/draw_xeven_pixel
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/draw_xodd_pixel
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/line_buffer_xeven_q
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/line_buffer_xodd_q
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/vdp_s0_sp_collision_incidence
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/vdp_s3_s4_sp_collision_x
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/vdp_s5_s6_sp_collision_y
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/reg_r1_sp_size
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/reg_r1_sp_zoom
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/reg_r8_col0_on
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/sp_mode2
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/vram_q
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/vram_a
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_render_read_address
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/ff_current_render_sp
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_attribute_address
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_y_address
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_x_address
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_pattern_num_address
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_pattern_l_address
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_pattern_r_address
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_color_address
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_y_pos
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/ff_render_y
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/ff_render_x
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/ff_render_pattern_l
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/ff_render_pattern_r
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/ff_render_pattern_num
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/ff_render_color
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/ff_render_ic
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/ff_render_cc
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/ff_render_ec
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/ff_draw_sp_num
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/ff_draw_state
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_draw_enable_8x8_normal
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_draw_enable_8x8_zoom
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_draw_enable_16x16_normal
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_draw_enable_16x16_zoom
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_draw_enable
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_draw_read
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_draw_write
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_draw_x0_pixel
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_draw_x1_pixel
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/ff_draw_x0
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/ff_draw_x1
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/ff_draw_pattern
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/ff_draw_color
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/ff_draw_ic
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/ff_draw_cc
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/ff_sp_enable
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_sp_final
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/ff_sp_final
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_draw_pattern_x0
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_draw_pattern_x1
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_line_buffer_x0_q
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_line_buffer_x1_q
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_draw_x0_last_active
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_draw_x0_last_sp_num
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_draw_x0_last_color
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_draw_x1_last_active
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_draw_x1_last_sp_num
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_draw_x1_last_color
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_draw_opacity
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/ff_vdp_s0_sp_collision_incidence
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/ff_vdp_s3456_sp_collision_xy_hold
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/ff_vdp_s3_s4_sp_collision_x
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/ff_vdp_s5_s6_sp_collision_y
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_next_render_sp
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/clk21m
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/reset
add wave -noupdate -radix binary /tb/u_dut/u_sprite_draw/dot_state
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/sp_draw_state
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/sp_en
add wave -noupdate -radix unsigned /tb/u_dut/u_sprite_draw/dot_counter_x
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/eight_dot_state
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/current_y
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/attribute_table_address
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/pattern_gentbl_address
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/vdp_s0_reset_timing
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/vdp_s5_reset_timing
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/current_render_sp
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/render_sp
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/render_sp_num
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/draw_xeven_adr
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/draw_xodd_adr
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/draw_xeven_write
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/draw_xodd_write
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/draw_xeven_pixel
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/draw_xodd_pixel
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/line_buffer_xeven_q
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/line_buffer_xodd_q
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/vdp_s0_sp_collision_incidence
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/vdp_s3_s4_sp_collision_x
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/vdp_s5_s6_sp_collision_y
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/reg_r1_sp_size
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/reg_r1_sp_zoom
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/reg_r8_col0_on
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/sp_mode2
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/vram_q
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/vram_a
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_render_read_address
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/ff_current_render_sp
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_attribute_address
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_y_address
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_x_address
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_pattern_num_address
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_pattern_l_address
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_pattern_r_address
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_color_address
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_y_pos
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/ff_render_y
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/ff_render_x
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/ff_render_pattern_l
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/ff_render_pattern_r
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/ff_render_pattern_num
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/ff_render_color
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/ff_render_ic
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/ff_render_cc
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/ff_render_ec
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/ff_draw_sp_num
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/ff_draw_state
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_draw_enable_8x8_normal
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_draw_enable_8x8_zoom
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_draw_enable_16x16_normal
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_draw_enable_16x16_zoom
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_draw_enable
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_draw_read
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_draw_write
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_draw_x0_pixel
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_draw_x1_pixel
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/ff_draw_x0
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/ff_draw_x1
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/ff_draw_pattern
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/ff_draw_color
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/ff_draw_ic
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/ff_draw_cc
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/ff_sp_enable
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_sp_final
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/ff_sp_final
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_draw_pattern_x0
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_draw_pattern_x1
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_line_buffer_x0_q
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_line_buffer_x1_q
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_draw_x0_last_active
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_draw_x0_last_sp_num
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_draw_x0_last_color
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_draw_x1_last_active
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_draw_x1_last_sp_num
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_draw_x1_last_color
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_draw_opacity
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/ff_vdp_s0_sp_collision_incidence
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/ff_vdp_s3456_sp_collision_xy_hold
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/ff_vdp_s3_s4_sp_collision_x
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/ff_vdp_s5_s6_sp_collision_y
add wave -noupdate -radix hexadecimal /tb/u_dut/u_sprite_draw/w_next_render_sp
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {584648409 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 287
configure wave -valuecolwidth 40
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {583108738 ps} {585365595 ps}
